name: Publish Android Bindings

on:
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: [self-hosted, Linux, small]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 10
      - name: Build and Publish Bindings
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        working-directory: ./
        run: |
          make ci

