name: Publish Android Bindings

on:
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: mco-dev-large-x64
    container: mobilecoin/android-bindings-builder:latest
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
      with:
        submodules: recursive
    - name: Build and Publish Bindings
      shell: bash
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      working-directory: ./
      run: |
        make ci

