name: Publish Android Bindings

on:
  workflow_dispatch:

jobs:
  build_publish:
    runs-on: mco-dev-small-x64
    container:
      image: gcr.io/mobilenode-211420/android-bindings-builder:1_4
      env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      volumes:
        - ./:/home/rust
        - /tmp/build/deps/:/usr/local/cargo/git
      options:
        -w /home/rust

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 10
      - name: Build and Publish Bindings
        working-directory: ./
        run: |
          make publish

