name: Publish Build Docker Image

on:
  workflow_dispatch: {}

jobs:
  build_and_publish_docker:
    runs-on: mco-dev-small-x64
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0
    - name: Docker
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: docker/Dockerfile
        context: docker/
        images: mobilecoin/android-bindings-builder
        tags: |
          ${{ github.ref_name }}
          type=sha
        flavor: |
          latest=true
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
